name: Build-wheels

# Description TK

on:
  push:  # TURN OFF
  pull_request:
  workflow_dispatch:

jobs:
  build-conda:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}  # needed for conda persistence
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up environment
      run: |
        conda config --append channels conda-forge
        conda install cython numpy clang llvm-openmp
    - name: Build wheel
      run: |
        git checkout v0.6
        python setup.py bdist_wheel
    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist/*.whl
