name: Cross-compatibility

# This workflow runs the Pandana unit tests across a comprehensive range of Python
# versions and operating systems. Windows needs conda in order to install geospatial
# dependencies.

on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  build-pip:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Pandana
      run: |
        pip install .
        pip install osmnet
    - name: Run demo
      run: |
        python examples/simple_example.py
    - name: Run unit tests
      run: |
        pip install pytest
        pytest -s

  build-conda:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}  # needed for conda persistence
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Pandana
      run: |
        pip install .

# OSMNet is causing a version of Pandas to be installed that crashes in GitHub Actions.
# Assume this will resolve itself on its own. (11-May-2021)

#        conda install osmnet --channel conda-forge
    - name: Run demo
      run: |
        python examples/simple_example.py
#    - name: Run unit tests
#      run: |
#        pip install pytest
#        pytest -s
