name: Cross-compatibility

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      if: (matrix.os != 'windows-latest') && (matrix.python-version != '3.9')
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Python ${{ matrix.python-version }} (Conda - for win and py39)
      if: (matrix.os == 'windows-latest') || (matrix.python-version == '3.9')
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install PyTables (py39 only)
      if: matrix.python-version == '3.9'
      run: |
        conda install pytables
    - name: Install OSMnet (pip - for mac and ubuntu)
      if: matrix.os != 'windows-latest'
      run: |
        pip install osmnet
    - name: Install Pandana from source code
      run: |
        pip install .
    - name: Run demo
      run: |
        python examples/simple_example.py
    - name: Run unit tests (skipped on windows)
      if: matrix.os != 'windows-latest'
      run: |
        pip install 'pytest<4.0'
        python setup.py test

# Unit tests are skipped on Windows because they're not passing currently.

# The Python 3.9 builds need Conda because there's no py39 binary for PyTables
# yet through pip. When one shows up at the following link, py39 can be
# incorporated into the standard os-based workflows.
# https://pypi.org/project/tables/#files 
