name: Python CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Compile and install Pandana and core dependencies
      run: pip install .
    - name: Install extras
      run: |
        pip install -r requirements-dev.txt
        pip install -r requirements-extras.txt
    - name: Environment diagnostics
      run: | 
        pip list
        pip show pandana
    - name: Code style checks
      run: pycodestyle pandana
    - name: Unit tests
      run: python setup.py test --pytest-args "--cov pandana --cov-report term-missing"
      