name: Python CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Pandana no longer officially supports Python 2.7 and 3.5 because it's too much
        # trouble to distribute binaries, but we'll continue monitoring compatibility
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Pandana
      run: |
        pip install .
    - name: Install extras
      run: |
        pip install -r requirements-dev.txt
        pip install -r requirements-extras.txt
    - name: Print environment diagnostics
      run: | 
        pip list
        pip show pandana
    - name: Run unit tests
      run: |
        python setup.py test --pytest-args "--cov pandana --cov-report term-missing"
      